### ISSUE TITLE
svg_attach and canvas_attach still marked experimental

### ISSUE THREAD

**Issue by ccmitchellusa** [dojo/gfx#1]
Seems that canvas_attach is noop'd and has been experimental for a long time.  can probably prune.
svg_attach still seems useful, but maybe incomplete? for creating GFX shapes from existing SVG DOM to manipulate the svg with gfx api?

**Comment by cjolif** [comment]
I don't see canvas_attach it has probably already been pruned. For svg_attach, as time is passing by and @edurocher might need to help on more important pieces of code like charting maybe we should keep it experimental for now and plan for a future release in supported mode.
For the 2.0 projects what I would like is to _not_ store experimental code in the same repo as supported code. This will avoid the confusion we have today. I would think that we should have a gfx-experimental (or whateverproject-experimental) project that hold experimental code. Kind of incubation project.

**Comment by edurocher** [comment]
Moved svg_attach to https://github.com/edurocher/gfx (to be migrated under ibm_dojo/ later).
