### ISSUE TITLE
Add minified version of gfx to /dist

### ISSUE THREAD

**Issue by ccmitchellusa** [dojo/gfx#3]
add a minified version of gfx to /dist/gfx-min.js to eliminate the need for building layers.  

This would be AMD-compatible layer and include deps like dojox/string/BidiEngine. 

Consider adding non-AMD built script (loader built in) as well for non-AMD crowd.

**Comment by cjolif** [comment]
I think we decided that separate projects will host the build version of each of your projects. So I think we can close that one.
